package config

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestConfig(t *testing.T) {
	t.Run("uses safe local defaults", func(t *testing.T) {
		cleanEnvironment(t)
		cfg, err := Load()
		require.NoError(t, err)
		assert.Equal(t, "development", cfg.Environment)
		assert.Equal(t, "8080", cfg.Port)
		assert.Equal(t, "info", cfg.LogLevel)
		assert.Equal(t, "storage/miniform.development.db", cfg.DatabasePath)
		assert.Equal(t, 200, cfg.MaxInputFields)
		assert.Equal(t, 64*1024, cfg.MaxPayloadBytes)
		assert.Equal(t, int64(1024*1024*1024), cfg.MaxUploadStorageBytes)
		assert.Equal(t, 32, cfg.RequestConcurrency)
		assert.Equal(t, 120, cfg.PublicGlobalRateLimit)
		assert.Equal(t, ProxyDirect, cfg.ProxyMode())
		assert.Equal(t, "miniform_session", cfg.SessionCookieName())
		assert.Equal(t, "X-Miniform-Signature", cfg.Webhook.SignatureHeader)
		assert.NotEmpty(t, cfg.SessionSecret)
		_, err = os.Stat("storage")
		assert.True(t, os.IsNotExist(err))
	})

	t.Run("applies every Miniform environment override", func(t *testing.T) {
		cleanEnvironment(t)
		values := map[string]string{
			"MINIFORM_ENV": "production", "MINIFORM_SESSION_SECRET": strings.Repeat("s", 32),
			"MINIFORM_PORT": "3000", "MINIFORM_DATA_DIR": "data", "MINIFORM_LOG_LEVEL": "debug",
			"MINIFORM_DATABASE_FILENAME": "custom.sqlite", "MINIFORM_LOGS_DIR": "logs",
			"MINIFORM_SESSION_TIMEOUT_SECONDS": "321", "MINIFORM_MAX_INPUT_FIELDS": "123",
			"MINIFORM_WEBHOOK_SIGNATURE_HEADER": "X-Signature", "MINIFORM_WEBHOOK_RETRY_LIMIT": "7",
			"MINIFORM_WEBHOOK_BACKOFF_SCHEDULE": "2,4,8",
		}
		for key, value := range values {
			t.Setenv(key, value)
		}
		cfg, err := Load()
		require.NoError(t, err)
		assert.Equal(t, "3000", cfg.Port)
		assert.Equal(t, "data/custom.production.sqlite", cfg.DatabasePath)
		assert.Equal(t, "logs", cfg.LogsDirectory)
		assert.Equal(t, 321, cfg.SessionTimeout)
		assert.Equal(t, 123, cfg.MaxInputFields)
		assert.Equal(t, WebhookConfig{"X-Signature", 7, "2,4,8"}, cfg.Webhook)
		assert.Equal(t, "__Host-miniform_session", cfg.SessionCookieName())
		assert.Equal(t, 10, cfg.GetMaxOpenConns())
	})

	t.Run("rejects short production session secrets", func(t *testing.T) {
		cleanEnvironment(t)
		t.Setenv("MINIFORM_ENV", "production")
		t.Setenv("MINIFORM_SESSION_SECRET", "too-short")

		_, err := Load()

		assert.ErrorContains(t, err, "at least 32")
	})

	t.Run("detects the Railway trusted proxy contract", func(t *testing.T) {
		cleanEnvironment(t)
		t.Setenv("MINIFORM_ENV", "production")
		t.Setenv("MINIFORM_SESSION_SECRET", strings.Repeat("r", 32))
		t.Setenv("RAILWAY_ENVIRONMENT_ID", "environment-id")
		t.Setenv("MATCHA_MANAGER_VERSION", "also-set")

		cfg, err := Load()

		require.NoError(t, err)
		assert.Equal(t, ProxyRailway, cfg.ProxyMode())
	})

	t.Run("preserves an explicit error log level", func(t *testing.T) {
		cleanEnvironment(t)
		t.Setenv("MINIFORM_ENV", "test")
		t.Setenv("MINIFORM_LOG_LEVEL", "error")

		cfg, err := Load()
		require.NoError(t, err)
		assert.Equal(t, "error", cfg.LogLevel)
	})

	t.Run("normalizes supported log levels", func(t *testing.T) {
		for input, expected := range map[string]string{
			"DEBUG":   "debug",
			"info":    "info",
			"warning": "warn",
			"ERROR":   "error",
		} {
			t.Run(input, func(t *testing.T) {
				cleanEnvironment(t)
				t.Setenv("MINIFORM_LOG_LEVEL", input)

				cfg, err := Load()

				require.NoError(t, err)
				assert.Equal(t, expected, cfg.LogLevel)
			})
		}
	})

	t.Run("rejects unsupported log levels", func(t *testing.T) {
		cleanEnvironment(t)
		t.Setenv("MINIFORM_LOG_LEVEL", "verbose")

		_, err := Load()

		assert.ErrorContains(t, err, "MINIFORM_LOG_LEVEL")
	})

	t.Run("accepts the session secret generated by Matcha", func(t *testing.T) {
		cleanEnvironment(t)
		t.Setenv("MINIFORM_ENV", "production")
		t.Setenv("PRIVATE_KEY", strings.Repeat("m", 32))
		t.Setenv("MATCHA_MANAGER_VERSION", "v1.2.3")

		cfg, err := Load()
		require.NoError(t, err)
		assert.Equal(t, strings.Repeat("m", 32), cfg.SessionSecret)
		assert.Equal(t, ProxyMatcha, cfg.ProxyMode())
	})

	t.Run("rejects invalid environment", func(t *testing.T) {
		cleanEnvironment(t)
		t.Setenv("MINIFORM_ENV", "staging")
		_, err := Load()
		assert.Error(t, err)
	})

	t.Run("rejects invalid HTTP ports", func(t *testing.T) {
		for _, port := range []string{"0", "65536", "not-a-port"} {
			t.Run(port, func(t *testing.T) {
				cleanEnvironment(t)
				t.Setenv("MINIFORM_PORT", port)
				_, err := Load()
				assert.ErrorContains(t, err, "MINIFORM_PORT")
			})
		}
	})

	t.Run("rejects invalid positive integer settings", func(t *testing.T) {
		for _, key := range []string{
			"MINIFORM_SESSION_TIMEOUT_SECONDS",
			"MINIFORM_MAX_INPUT_FIELDS",
			"MINIFORM_WEBHOOK_RETRY_LIMIT",
		} {
			t.Run(key, func(t *testing.T) {
				for _, value := range []string{"0", "-1", "not-a-number"} {
					t.Run(value, func(t *testing.T) {
						cleanEnvironment(t)
						t.Setenv(key, value)

						_, err := Load()

						assert.ErrorContains(t, err, key)
					})
				}
			})
		}
	})

	t.Run("rejects invalid webhook backoff schedules", func(t *testing.T) {
		for _, schedule := range []string{"0", "-1", "1,nope,3", "1,,3"} {
			t.Run(schedule, func(t *testing.T) {
				cleanEnvironment(t)
				t.Setenv("MINIFORM_WEBHOOK_BACKOFF_SCHEDULE", schedule)

				_, err := Load()

				assert.ErrorContains(t, err, "MINIFORM_WEBHOOK_BACKOFF_SCHEDULE")
			})
		}
	})

	t.Run("rejects paths passed as a database filename", func(t *testing.T) {
		for _, filename := range []string{
			filepath.Join(string(filepath.Separator), "tmp", "miniform.db"),
			filepath.Join("nested", "miniform.db"),
			filepath.Join("..", "miniform.db"),
			".",
			"..",
		} {
			t.Run(filename, func(t *testing.T) {
				cleanEnvironment(t)
				t.Setenv("MINIFORM_DATABASE_FILENAME", filename)

				_, err := Load()

				assert.ErrorContains(t, err, "MINIFORM_DATABASE_PATH")
			})
		}
	})

	t.Run("rejects invalid webhook signature header names", func(t *testing.T) {
		tests := []struct {
			name   string
			header string
		}{
			{name: "space", header: "Bad Header"},
			{name: "line break", header: "X-Signature\r\nInjected"},
		}
		for _, tt := range tests {
			t.Run(tt.name, func(t *testing.T) {
				cleanEnvironment(t)
				t.Setenv("MINIFORM_WEBHOOK_SIGNATURE_HEADER", tt.header)

				_, err := Load()

				assert.ErrorContains(t, err, "MINIFORM_WEBHOOK_SIGNATURE_HEADER")
			})
		}
	})

	t.Run("loads dotenv without overriding the process environment", func(t *testing.T) {
		cleanEnvironment(t)
		require.NoError(t, os.WriteFile(".env", []byte("MINIFORM_PORT=9999\nMINIFORM_DATA_DIR=dotenv-data\n"), 0o600))
		t.Setenv("MINIFORM_PORT", "3000")

		cfg, err := Load()
		require.NoError(t, err)
		assert.Equal(t, "3000", cfg.Port)
		assert.Equal(t, "dotenv-data", cfg.DataDirectory)
	})

	t.Run("rejects malformed dotenv files", func(t *testing.T) {
		cleanEnvironment(t)
		require.NoError(t, os.WriteFile(".env", []byte("MINIFORM_PORT='unterminated\n"), 0o600))

		_, err := Load()
		assert.ErrorContains(t, err, "load .env")
	})

	t.Run("creates runtime directories only when requested", func(t *testing.T) {
		cleanEnvironment(t)
		t.Setenv("MINIFORM_DATA_DIR", "data")
		t.Setenv("MINIFORM_LOGS_DIR", "logs")
		t.Setenv("MINIFORM_DATABASE_PATH", filepath.Join("database", "nested", "miniform.db"))
		cfg, err := Load()
		require.NoError(t, err)
		require.NoError(t, cfg.EnsureDirectories())
		for _, directory := range []string{"data", "logs", filepath.Join("database", "nested")} {
			info, err := os.Stat(directory)
			require.NoError(t, err)
			assert.True(t, info.IsDir())
		}
	})

	t.Run("parses configured retry delays", func(t *testing.T) {
		cfg := &Config{Webhook: WebhookConfig{BackoffSchedule: " 2, 8 "}}
		assert.Equal(t, []int{2, 8}, cfg.WebhookBackoff())
		cfg.Webhook.BackoffSchedule = "2,invalid,8"
		assert.Equal(t, []int{1, 5, 15, 60}, cfg.WebhookBackoff())
	})
}

func cleanEnvironment(t *testing.T) {
	t.Helper()
	original := os.Environ()
	os.Clearenv()
	t.Chdir(t.TempDir())
	t.Cleanup(func() {
		os.Clearenv()
		for _, entry := range original {
			key, value, _ := strings.Cut(entry, "=")
			_ = os.Setenv(key, value)
		}
	})
}
